### PR TITLE
Allow explicit timestamps for Span start/end.

### PR DESCRIPTION
**Pull request by carlosalberto**

### CODE REVIEW

**Comment by carlosalberto** [comment]
Addresses #24 

One thing that that mentioned was that OT uses microseconds - which might not be the case for this new API ;)

**Comment by tylerbenson** [comment]
FWIW, I am strongly in favor of NOT using micros.  I would rather see something like `TimeUnit` as a second argument.

**Comment by yurishkuro** [comment]
> FWIW, I am strongly in favor of NOT using micros. I would rather see something like TimeUnit as a second argument.

+1


Why are there 34 files in this PR? Doesn't seem to match the title.

**Comment by bogdandrutu** [comment]
Should this be closed because of https://github.com/bogdandrutu/openconsensus/pull/43?

**Comment by SergeyKanzhelev** [comment]
Closing this as I believe current decision is to use `SpanData` for these scenarios

**Pull request closed without merging**
