### PR TITLE
Make core classes interfaces and provide default abstract classes.

### PR DESCRIPTION
**Pull request by carlosalberto**
Addresses #19

### CODE REVIEW

**Comment by carlosalberto** [comment]
Implemented this part of core classes only, namely: Tracer, TracerComponent, Span, SpanBuilder, SpanContext, PropagationComponent, TextFormat and BinaryFormat.

**Comment by carlosalberto** [comment]
@bogdandrutu Works. Will update it.

**Comment by tedsuo** [comment]
If we support both interfaces and abstract classes, the surface area will get very large. Ideally, I would prefer we only support interfaces, and remove the abstract classes for now. 

Possibly the abstract classes could go in a separate package, which we can add at a later date.

**Comment by yurishkuro** [comment]
Package or even different artifact. The API artifact doesn't need "base" classes, so I would suggest not including them there. Base classes are really just a convenience for implementations, a convenience that some of them may not want (since there are a requirement for pure interfaces). I would suggest keeping them inside the implementation artifact for now, until someone explicitly requests the base classes to be in a separate artifact (so that they don't pull transitive deps from default impl).

**Comment by bogdandrutu** [comment]
Based on the comments, I think we need to remove the Abstract classes from the api artifact and keep everything an interface for the moment. Do I understand this correctly?

**Comment by carlosalberto** [comment]
Closing this one on behalf of #194

**Pull request closed without merging**
