### PR TITLE
Add a boolean field to set a Span as asynchronous.

### PR DESCRIPTION
**Pull request by carlosalberto**
Addresses part of  #14

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Can you add more details into issue why is it needed. I believe we wanted to defer adding this field for later

**Comment by carlosalberto** [comment]
hey hey @SergeyKanzhelev 

I'm adding children `Span` support in the OT shim and wanted to add this (`FOLLOWS_FROM` there). Not super important though ;)

**Comment by SergeyKanzhelev** [comment]
@carlosalberto I believe @yurishkuro has problem with calling it `async`. So perhaps close this PR for now?

**Comment by carlosalberto** [comment]
If the problem is the name (which I can understand), we can still keep this PR and update the name ;)

**Comment by bogdandrutu** [comment]
@carlosalberto let's see how you can do with the name :)

**Comment by carlosalberto** [comment]
@yurishkuro Any suggestion on the name here? ;)

**Comment by SergeyKanzhelev** [comment]
I believe we decided to close this PR and come back to it later when we will agree on changes needed

**Pull request closed without merging**
