### PR TITLE
Remove support for long values in Metrics

### PR DESCRIPTION
**Pull request by bogdandrutu**
This is based on https://github.com/OpenObservability/OpenMetrics/issues/132.

Even if they decide to keep the ability to export gauge with long or double, we can get that information in the Options and use it only during the export. Accumulated longs using doubles gives us a good approximation and more importantly simplifies the API.

### CODE REVIEW

**Comment by bogdandrutu** [comment]
If you think it is useful we can keep it, but Prometheus for example has only double. I need feedback on this. I am half convinced :)

**Comment by SergeyKanzhelev** [comment]
It may be useful for API, not for export format itself. So on API layer you have differentiation and then it all reported as `doubles`. 

Any other opinions?

**Comment by SergeyKanzhelev** [comment]
For reference - MicroMeter allow gauge of any `Number` type: https://micrometer.io/docs/concepts#_gauges

**Comment by bogdandrutu** [comment]
@SergeyKanzhelev you are correct, but look what they do after https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java#L449 they convert everything to double. 

I think we can always add the support for other types later if needed, what do you think? Or we do offer support for any "Number" but that will be a problem in my opinion because that forces boxing.

**Comment by SergeyKanzhelev** [comment]
Makes sense. I already approved anyway.

BTW, do you think it's a good idea to ask for feedback on API from somebody from micrometer?

**Comment by bogdandrutu** [comment]
I will continue to chat about this with OpenMetrics and maybe other metrics experts to get more details.

**Pull request closed without merging**
