### PR TITLE
Remove all deprecated APIs/classes from OpenCensus shim.

### PR DESCRIPTION
**Pull request by songy23**
Updates https://github.com/bogdandrutu/openconsensus/issues/104.

We don't need to worry about backwards compatibility on deprecated stuffs in the new project.

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
We need to think of people who already took dependency on OpenCensus and how they will migrate to OpenConsensus. There should be no-op to adopt this shim. And one step is to adopt the OpenConsensus. Making it two steps - first adopt shim and remove all deprecated references and than adopt OpenConsensus iw much worse and will block adoption.

I'd say we should keep deprecated APIs redirection unless we know for sure nobody is using those

**Comment by songy23** [comment]
Most of the deprecated APIs are either performing noop or redirected to other non-deprecated OpenCensus APIs. Therefore IMO we don't need to explicit redirect them to OpenConsensus APIs.

/cc @bogdandrutu WDYT?

**Comment by bogdandrutu** [comment]
Deprecated methods can be redirected to other non deprecated methods.

**Comment by bogdandrutu** [comment]
I think we need the full picture here so I suggest to not remove them

**Comment by songy23** [comment]
Make sense to me.

**Pull request closed without merging**
